// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPTQ5DQXS3dz1SI5aPN3Dsgu11OUSE-9c',
    appId: '1:571714783418:android:19e70b1f4bfaa8228d5a83',
    messagingSenderId: '571714783418',
    projectId: 'endless-fire-468401-f8',
    storageBucket: 'endless-fire-468401-f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP_21tFOvq-DaQojYL_N2zCYUkoW9R3sA',
    appId: '1:571714783418:ios:968666332198c1298d5a83',
    messagingSenderId: '571714783418',
    projectId: 'endless-fire-468401-f8',
    storageBucket: 'endless-fire-468401-f8.firebasestorage.app',
    androidClientId: '571714783418-5f3j4et9v42ufqhhtnvgdvl1b0bng32i.apps.googleusercontent.com',
    iosClientId: '571714783418-7vqc3i8lbgboap6o4ns8sm8oo3055d32.apps.googleusercontent.com',
    iosBundleId: 'com.easyo.babysitterHam',
  );
}
